### ISSUE TITLE
Criação concepção 5w2h

### ISSUE THREAD

**Issue by JoGabTasca** [Projetos-de-Extensao/PBE_24.2_8001_III_Pandora#1]
- [x] Pesquisa de mercado
- [x] Definir tema do aplicativo
- [x] Selecione as 3 principais funcionalidades
- [x] Documento 5w2h

**Comment by ewerside** [comment]
Proposta de 3 principais funcionalidades:
- Streaming de áudio principal;
- Acesso a resenhas e outros conteúdos sobre o livro, bem como músicas e trilha sonora de filmes e séries relacionados;
- Reprodução simultânea de sons e músicas relaxantes durante a reprodução do audiobook (ex: sons de chuva);

Se tiverem outras ideias, adicionem abaixo:
